// <auto-generated />
using System;
using ExpressEats.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpressEats.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    [Migration("20210913155448_secondmigration")]
    partial class secondmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ExpressEats.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Snacks",
                            Description = "The most versatile and fresh medium"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Lunch",
                            Description = "The most versatile and fresh medium"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Dinner",
                            Description = "The most versatile and fresh medium"
                        });
                });

            modelBuilder.Entity("ExpressEats.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDishOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            CategoryName = "Snacks",
                            DishName = "Pohe",
                            ImageThumbnailUrl = "/images/Poha.jpg",
                            ImageUrl = "/images/Poha.jpg",
                            IsDishOfTheWeek = false,
                            LongDescription = "Best Snacks for hunger",
                            Price = 15m,
                            ShortDescription = "Teasty Snacks"
                        },
                        new
                        {
                            FoodId = 2,
                            CategoryName = "Lunch",
                            DishName = "Biryani",
                            ImageThumbnailUrl = "/images/Biryani.jpg",
                            ImageUrl = "/images/Biryani.jpg",
                            IsDishOfTheWeek = false,
                            LongDescription = "Rich Spices flavoured veg biryani",
                            Price = 180m,
                            ShortDescription = "Veg Biryani"
                        },
                        new
                        {
                            FoodId = 3,
                            CategoryName = "Snacks",
                            DishName = "Vadapav",
                            ImageThumbnailUrl = "/images/vadapav.jpg",
                            ImageUrl = "/images/vadapav.jpg",
                            IsDishOfTheWeek = false,
                            LongDescription = "Mumbai special vadapav",
                            Price = 15m,
                            ShortDescription = "Teasty Snacks"
                        });
                });

            modelBuilder.Entity("ExpressEats.Models.Food", b =>
                {
                    b.HasOne("ExpressEats.Models.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ExpressEats.Models.Category", b =>
                {
                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
